### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ogitaniryosuke** [ogitaniryosuke/furima-39277#20]
# URL
https://furima-39277.onrender.com

# Basic認証のIDとパスワード
       ID : gtnr
       password :  7777

 # 出品者用のメールアドレスとパスワード
        address : a@a
        password : a111111

 # 購入者用のメールアドレスとパスワード
        address : b@b
        password : b111111

**Comment by mo1015** [comment]
@ogitaniryosuke さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン状態の場合は、自身が出品した販売中商品の商品情報編集ページに遷移できること**
「商品の編集」ボタンを押すとトップページに遷移してしまい、編集ページに遷移できません。


- [ ] **ログイン状態の場合にのみ、自身が出品した商品情報を削除できること**
削除ボタンを押しても削除ができません。

- [ ] **配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であること**
「都道府県」を入力しなくても購入ができてしまいます。

- [ ] **購入機能にて、エラーハンドリングの際、重複したエラーメッセージが表示されないこと**
「Phone number can't be blank」というエラーメッセージが重複しています。

**※編集、削除機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。**

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ogitaniryosuke** [comment]
# what
挙動確認をお願いします！

 # why
指摘いただいた下記修正箇所の修正が完了したためです。

[修正依頼箇所]

- [ ]  ログイン状態の場合は、自身が出品した販売中商品の商品情報編集ページに遷移できること

「商品の編集」ボタンを押すとトップページに遷移してしまい、編集ページに遷移できません。

- [ ]  ログイン状態の場合にのみ、自身が出品した商品情報を削除できること
削除ボタンを押しても削除ができません。

- [ ]  配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であること
「都道府県」を入力しなくても購入ができてしまいます。

- [ ]  購入機能にて、エラーハンドリングの際、重複したエラーメッセージが表示されないこと
「Phone number can't be blank」というエラーメッセージが重複しています。

下記のリンクよりご確認のほど、よろしくお願いいたします。
https://github.com/ogitaniryosuke/furima-39277/issues/20#issue-1732384654

**Comment by ogitaniryosuke** [comment]
# what
挙動確認をお願いします！

 # why
指摘いただいた下記修正箇所の修正が完了したためです。
------

[修正依頼箇所]
- [x] **ログイン状態の場合でも、自身が出品していない商品の商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらずトップページに遷移すること**
自身が出品していない商品の編集ページに遷移できてしまいます。

- [x] **ログイン状態の場合でも、自身が出品した売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移すること**
出品者以外のユーザーが、売却済みの商品の商品情報編集ページにURLを直接入力して遷移しようとすると遷移できてしまいます。

- [x] **編集が完了したら、商品詳細表示ページに遷移し、変更された商品情報が表示されること**
編集後にトップページに遷移してしまうため、詳細ページに遷移するよう実装をお願いします。
----------


# URL
https://furima-39277.onrender.com

# Basic認証のIDとパスワード
       ID : gtnr
       password :  7777

 # 出品者用のメールアドレスとパスワード
        address : a@a
        password : a111111

 # 購入者用のメールアドレスとパスワード
        address : b@b
        password : b111111
